typography_spectrum: 0.5986489795614034
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.0966914864256978
  lightness: 0.794852833263576
  saturation: 0.2402510172687471
  rhythmicContrast: 0.30317937047220767
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.0017299419268965721
analytics:
  google: null
  facebook: null
  twitter: null
name: Vorhaus Communications
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Vorhaus Communications, Inc.'
description: 'Whoever Tells the Best Story, Wins.'
purpose: []
